Request evidence
fobnail/fobnail pull request #21
Opened 2022-03-23 15:59 UTC by arturkow2000

2022-04-01 14:46 UTC, krystian-hebel requested changes

2022-04-01 14:46 UTC, krystian-hebel commented on src/client/proto.rs
> +        // identity map raw values into corresponding enum constants. Rust if free
```suggestion
        // identity map raw values into corresponding enum constants. Rust is free
```

2022-04-01 14:46 UTC, krystian-hebel commented on src/client/proto.rs
> +#[repr(u32)]
Shouldn't `u16` be used instead?

2022-04-01 14:46 UTC, krystian-hebel commented on src/client/proto.rs
> +            Self::Unknown(u) => write!(f, "unknown (0x{:x})", u),
```suggestion
            Self::Unknown(u) => write!(f, "unknown (0x{:04x})", u),
```
or `"unknown ({:#06x})"`. Full length u16 should be more readable than shortened version.

2022-04-01 14:46 UTC, krystian-hebel commented on src/client/proto.rs
> +                "PCR count does not match, count from mask is {}, but really there are {} PCRs",
This doesn't get printed even if counts don't match. Depending on number of bits in `pcrs` next error about expected PCR size may be printed instead (if number of PCR values in not a multiply of bits set). Seems that both `n1` and `n2` are the same as number of bits in `pcrs`.

2022-04-04 11:51 UTC, arturkow2000 commented on src/client/proto.rs
> +#[repr(u32)]
Right, fixed

2022-04-05 14:27 UTC, krystian-hebel commented on src/client/proto.rs
> +                "PCR count does not match, count from mask is {}, but really there are {} PCRs",
Ok, it was my error during testing. This works as expected.

2022-04-05 14:28 UTC, krystian-hebel approved these changes

2022-04-05 14:31 UTC, merged