Receive and verify AIK key
fobnail/fobnail pull request #7
Opened 2022-02-03 16:45 UTC by arturkow2000

2022-03-03 15:36 UTC, krystian-hebel requested changes

2022-03-03 15:36 UTC, krystian-hebel commented on pal/pal_pc/src/trussed/store.rs
>      const BLOCK_SIZE: usize = 4096;
Can we make it smaller in order to waste less space per directory?

2022-03-03 15:36 UTC, krystian-hebel commented on src/certmgr/verify.rs
> +                        self.iter_certificates(organization, trussed).collect();
Is it possible to return vector of file names (or paths if they are in different directories) instead and load full file contents inside `for` loop below?

2022-03-03 15:36 UTC, krystian-hebel commented on src/client/mod.rs
> +                        core::mem::swap(data, &mut aik);
I don't know about Rust's memory management, but shouldn't this be swapped back to initial `data` so it is properly freed?

2022-03-03 15:36 UTC, krystian-hebel commented on src/client/mod.rs
> +                    // TODO: should set Content-Type header to CBOR
```suggestion
                    request.message.set_content_format(coap_lite::ContentFormat::ApplicationCBOR);
```

This isn't checked on Attester side right now, but at some point we may depend on it.

2022-03-03 15:36 UTC, krystian-hebel commented on src/client/mod.rs
> +                        core::mem::swap(data, &mut aik);
OK, I notices it is done in `handle_server_response()`. Maybe mention this in comments, here and in `handle_server_response()`?

2022-03-03 15:36 UTC, krystian-hebel commented on src/client/state.rs
>      // InitDataReceived and RequestMetadata
Already done
```suggestion
```

2022-03-03 15:36 UTC, krystian-hebel commented on src/client/tpm/kdf.rs
> +    // lack of RSA support (and possibly for other reasons two).
```suggestion
    // lack of RSA support (and possibly for other reasons too).
```

2022-03-03 15:36 UTC, krystian-hebel commented on src/client/tpm/mod.rs
> +                // panic!("AES key = {:#x?}", aes_key);
Remove

2022-03-03 15:36 UTC, krystian-hebel commented on src/client/tpm/mu.rs
> +                );
No, it is present, but it is `TPM2_ALG_NULL`. In that case its other fields (`keyBits`, `mode`, `details`) do not exist. This is easy to miss in TPM specification, it is hidden somewhere behind the definition of `+` symbol either prepended or appended to type name. Same is true for `scheme` - it is also `TPM2_ALG_NULL` so it has no `details`. In the current code what should be `symmetric.algorithm` is read as `scheme.scheme`, and what should be `scheme.scheme` is read as `scheme.detail`.

```suggestion
                let symmetric_algorithm_id = Algorithm::try_from_u8(decode!(cursor, data, u16))?;
                ensure!(
                    symmetric_algorithm_id.is_null(),
                    "Non-null symmetric algorithm, this is not supported"
                );
                
                let rsa_scheme = Algorithm::try_from_u8(decode!(cursor, data, u16))?;
                ensure!(
                    rsa_scheme.is_null(),
                    "Non-null scheme, this is not supported"
                );
```

2022-03-03 15:37 UTC, krystian-hebel commented on pal/pal_pc/src/trussed/store.rs
>      const BLOCK_SIZE: usize = 4096;
No, we can't, this is flash erase granularity.

2022-03-04 09:47 UTC, arturkow2000 commented on src/certmgr/verify.rs
> +                        self.iter_certificates(organization, trussed).collect();
@krystian-hebel I modified `iter_certificates()` a bit so we can now call verify_internal while iterating.

2022-03-04 09:47 UTC, arturkow2000 commented on src/client/mod.rs
> +                    // TODO: should set Content-Type header to CBOR
Fixed

2022-03-04 09:49 UTC, arturkow2000 commented on src/client/tpm/mu.rs
> +                );
Fixed

2022-03-04 10:01 UTC, arturkow2000 commented on src/client/mod.rs
> +                        core::mem::swap(data, &mut aik);
@krystian-hebel I mentioned it.

> I don't know about Rust's memory management, but shouldn't this be swapped back to initial data so it is properly freed?

No. When `aik` goes out of scope, Vec descrutctor will be called and data will freed normally.

2022-03-07 17:54 UTC, macpijan commented
@arturkow2000 @krystian-hebel What's left to close this one?

2022-03-08 08:43 UTC, arturkow2000 commented
@krystian-hebel Anything left?

2022-03-08 11:08 UTC, krystian-hebel reviewed
One typo, otherwise LGTM

2022-03-08 11:08 UTC, krystian-hebel commented on src/client/tpm/mu.rs
> +        let buf_len: u16 = self.inner.len().try_into().expect("buffer to big for TPM");
```suggestion
        let buf_len: u16 = self.inner.len().try_into().expect("buffer too big for TPM");
```

2022-03-08 11:23 UTC, arturkow2000 commented on src/client/tpm/mu.rs
> +        let buf_len: u16 = self.inner.len().try_into().expect("buffer to big for TPM");
Fixed

2022-03-08 11:29 UTC, krystian-hebel approved these changes

2022-03-09 08:32 UTC, TomaszAIR commented
Merged

2022-03-09 08:32 UTC, merged